#!/bin/bash

# compile a package from the current directory instead of AUR
# Parameters:
#    1   - platform (as used by docker --platform)
#    2ff - further parameters are handed over to makepkg.
#          Common examples are -f --force --ignorearch
if [ -z "$1" ] ; then
	printf "Error: Missing platform (param 1)\n"
	exit 1
fi

# config
PLATFORM="$1" &&
shift &&

# common variables
OURSELVES=$(basename "${BASH_SOURCE[0]}") &&
BUILDIMG="ghcr.io/nafets227/archpackages:local-$OURSELVES"
true || exit 1

# Build our builder image
PRJDIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
docker build \
	-t "$BUILDIMG" \
	--platform "$PLATFORM" \
	"$PRJDIR/.github/actions/build-aur-packages" \
	&&

# finally run makepkg inside the builder image
docker run \
	--platform "$PLATFORM" \
	-v "$PWD:/home/builder" \
	-i \
	--user 1000 \
	"$BUILDIMG" \
	bash <<-EOF
		cd &&
		sudo bash -c "cat >>/etc/pacman.conf" <<-EOFPACMAN &&
			[nafets227-archPackages]
			SigLevel = Optional
			Server = https://nafets227.github.io/archPackages/\\\$arch/\\\$repo
			EOFPACMAN

		if [ -d /home/builder/localpkg ] ; then
			sudo bash -c "cat >>/etc/pacman.conf" <<-EOFPACMAN &&
				[nafets227-local]
				SigLevel = Optional
				Server = file:///home/builder/localpkg
				EOFPACMAN
			repo-add "/home/builder/localpkg/nafets227-local.db.tar.gz" \
				/home/builder/localpkg/*pkg*
		fi

		sudo pacman -Sy &&
		export LOGDEST=/home/builder/pkg
		makepkg --noconfirm --log -s $@ </dev/null &&
		makepkg --printsrcinfo >.SRCINFO
		EOF
