#!/bin/bash

# compile a package from the current directory instead of AUR
# Parameters:
#    1   - platform (as used by docker --platform)
#    2ff - further parameters are handed over to makepkg.
#          Common examples are -f --force --ignorearch
if [ -z "$1" ] ; then
	printf "Error: Missing platform (parm 1)\n"
	exit 1
fi

# config
PLATFORM="$1" &&
shift &&
BUILDAURTAG=$(
	grep "uses: .*build-aur-package" \
		"$(dirname "${BASH_SOURCE[0]}")/.github/workflows/makepkg.yaml" \
	| head -1 \
	| sed 's/^.*uses: //'
	)
if [ -z "$BUILDAURTAG" ] ; then
	printf "Error: Could not get BUILDAURTAG\n"
	exit 1
fi

# common variables
OURSELVES=$(basename "${BASH_SOURCE[0]}") &&
BUILDAURDIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")/build-aur-package &&
BUILDAURIMG="ghcr.io/nafets227/build-aur-packages:local-$OURSELVES"
true || exit 1

# clone or fetch+checkout build-aur-packages.
if [ -d "$BUILDAURDIR" ] ; then
	git -C "$BUILDAURDIR" fetch origin &&
	git -C "$BUILDAURDIR" fetch origin --tags &&
	true || exit 1
	if git -C "$BUILDAURDIR" tag | grep --quiet "^${BUILDAURTAG##*@}\$" ; then
		# $BUILDAURTAG is a tag, not a branch
		git -C "$BUILDAURDIR" checkout --detach "${BUILDAURTAG##*@}" &&
		true || exit 1
	else
		git -C "$BUILDAURDIR" checkout --detach "origin/${BUILDAURTAG##*@}" &&
		true || exit 1
	fi
else
	mkdir -p "$BUILDAURDIR" &&
	git \
		-c advice.detachedHead=false \
		clone \
		--depth 1 \
		"https://github.com/${BUILDAURTAG%@*}" \
		--branch "${BUILDAURTAG##*@}" \
		"$BUILDAURDIR" \
		&&
	true || exit 1
fi

# Build our builder image
docker build \
	-t "$BUILDAURIMG" \
	--platform "$PLATFORM" \
	"$BUILDAURDIR" \
	&&

# finally run makepkg inside the builder image
docker run \
	--platform "$PLATFORM" \
	-v "$PWD:/home/builder" \
	-i \
	--user 1000 \
	"$BUILDAURIMG" \
	bash <<-EOF
		cd &&
		sudo bash -c "cat >>/etc/pacman.conf" <<-EOFPACMAN &&
			[nafets227-archPackages]
			SigLevel = Optional
			Server = https://nafets227.github.io/archPackages/\\\$arch/\\\$repo
			EOFPACMAN
		sudo pacman -Sy &&
		export LOGDEST=/home/builder/pkg
		makepkg --noconfirm --log -s $@ </dev/null &&
		makepkg --printsrcinfo >.SRCINFO
		EOF
